let words: string[] = [
    'COMPUTADORA',
    'COMPUTADOR',
    'FEMPUTADORA',
    'AGUACATE',
    'VEHICULO',
    'ANIMAR',
    'MACKENZIE',
    'MACKENZIETHELITTLEENZIE',
    'ANIMAL',
    'VETERINARIO',
    'CELULAR',
    'TELEFONO',
    'CAZADOR',
    'MONEY',
    'MOBILE',
    'WIFI',
    'TENNESSEE',
    'MURFREESBORO',
    'ADAPTACION',
    'AGUDO',
    'ESTIMULACION',
    'HIGIENE',
    'EXECUTIONER',
    'REAPER',
    'ASSASSIN',
    'BUTCHER',
    'MASK',
    'FACE',
    'SUN',
    'RESET',
    'POWER',
    'DIANAMARADIAGO',
    'PIE',
    'BABY',
    'CALI',
    'HOT',
    'LAKE',
    'COLOMBIA',
    'UNITEDSTATES',
    'USA',
    'SMYRNA',
    'BEER',
    'WEED',
    'NEEDFORSPEED',
    'CHOCOLATE',
    'UBER',
    'MEDELLIN',
    'BOOBS',
    'HANGMAN',
    'AHORCADO',
    'SEX',
    'GALLBLADDER',
    'VESICULA',
    'ENGLISH',
    'INGLES',
    'SPANISH',
    'MOON',
    'HEADSMAN',
    'MURDERER',
    'SUBWAY',
    'SYNDROME',
    'AWKWARD',
    'GALAXY',
    'WORD',
    'COMPUTER',
    'CAR',
    'CELLPHONE',
    'MATRIX',
    'ABSURD',
    'LUCKY',
    'KEY',
    'ESPIONAGE',
    'TEAMOMIREINA',
    'LENGTH',
    'HEIGHT',
    'WEIGHT'
]



export function getRandomWord() {

    const randomIndex = Math.floor(Math.random() * words.length);

    return words[randomIndex]
}